package crawler

import (
	"context"
	"net/url"
	"strings"
	"time"

	"github.com/chromedp/chromedp"
	"golang.org/x/net/html"
)

// RenderedPage holds the results of JS-rendering a page.
type RenderedPage struct {
	HTML  string
	Forms []FormInfo
	Links []string
}

// RenderPage uses headless Chrome to render a JS-heavy page, then extracts
// forms and links from the fully-rendered DOM. This handles SPA pages where
// forms are generated by JavaScript (React, Vue, Angular).
func RenderPage(ctx context.Context, targetURL string, timeout time.Duration) (*RenderedPage, error) {
	if timeout <= 0 {
		timeout = 15 * time.Second
	}

	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.NoFirstRun,
		chromedp.NoDefaultBrowserCheck,
		chromedp.Headless,
		chromedp.DisableGPU,
		chromedp.NoSandbox,
		chromedp.IgnoreCertErrors,
		chromedp.WindowSize(1280, 800),
	)

	allocCtx, allocCancel := chromedp.NewExecAllocator(ctx, opts...)
	defer allocCancel()

	tabCtx, tabCancel := chromedp.NewContext(allocCtx)
	defer tabCancel()

	tctx, cancel := context.WithTimeout(tabCtx, timeout)
	defer cancel()

	var renderedHTML string
	err := chromedp.Run(tctx,
		chromedp.Navigate(targetURL),
		chromedp.WaitReady("body", chromedp.ByQuery),
		chromedp.Sleep(2*time.Second), // wait for async JS rendering
		chromedp.OuterHTML("html", &renderedHTML),
	)
	if err != nil {
		return nil, err
	}

	page := &RenderedPage{HTML: renderedHTML}
	page.Forms, _ = extractForms(renderedHTML, targetURL)

	// Extract links from rendered DOM
	base, err := url.Parse(targetURL)
	if err != nil {
		return page, nil
	}
	page.Links = extractLinksFromNode(renderedHTML, base)

	return page, nil
}

// extractLinksFromNode extracts href/src/action URLs from rendered HTML.
func extractLinksFromNode(body string, base *url.URL) []string {
	doc, err := html.Parse(strings.NewReader(body))
	if err != nil {
		return nil
	}

	seen := make(map[string]bool)
	var links []string

	var walk func(*html.Node)
	walk = func(n *html.Node) {
		if n.Type == html.ElementNode {
			for _, attr := range n.Attr {
				if attr.Key != "href" && attr.Key != "src" && attr.Key != "action" {
					continue
				}
				ref, err := url.Parse(attr.Val)
				if err != nil {
					continue
				}
				resolved := base.ResolveReference(ref).String()
				if resolved != "" && !seen[resolved] {
					seen[resolved] = true
					links = append(links, resolved)
				}
			}
		}
		for c := n.FirstChild; c != nil; c = c.NextSibling {
			walk(c)
		}
	}
	walk(doc)

	return links
}
